---
- name: install apache2 on ubuntu
  hosts: all
  become: yes
  tasks: 
    - name: install apache2
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
    - name: restart apache2
      ansible.builtin.service:
        name: apache2
        state: restart